-- ==============================================================================
-- NUVEM DE AÇÚCAR - ESQUEMA E SEED COMPLETO PARA SUPABASE (POSTGRESQL)
-- ==============================================================================
-- Instruções:
-- 1. Acesse o dashboard do seu projeto no Supabase (https://supabase.com/dashboard)
-- 2. No menu lateral esquerdo, clique no ícone "SQL Editor" (ícone com terminal)
-- 3. Clique no botão "New query"
-- 4. Cole todo o conteúdo deste arquivo e clique em "Run" (ou pressione Ctrl + Enter)
-- ==============================================================================

-- 1. CRIAÇÃO DA TABELA DE PRODUTOS
CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  price NUMERIC(10, 2) NOT NULL,
  flavor_tag TEXT NOT NULL,
  image_emoji TEXT NOT NULL,
  stock INTEGER NOT NULL DEFAULT 20,
  ingredients TEXT,
  details TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. CRIAÇÃO DA TABELA DE PEDIDOS
CREATE TABLE IF NOT EXISTS public.orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name TEXT NOT NULL,
  customer_email TEXT NOT NULL,
  delivery_address TEXT NOT NULL,
  customer_cep TEXT,
  estimated_delivery TEXT,
  payment_method TEXT NOT NULL,
  subtotal NUMERIC(10, 2) NOT NULL DEFAULT 0,
  discount NUMERIC(10, 2) NOT NULL DEFAULT 0,
  shipping_fee NUMERIC(10, 2) NOT NULL DEFAULT 0,
  coupon_code TEXT,
  total NUMERIC(10, 2) NOT NULL,
  status TEXT NOT NULL DEFAULT 'confirmado',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. CRIAÇÃO DA TABELA DE ITENS DO PEDIDO
CREATE TABLE IF NOT EXISTS public.order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  product_id BIGINT NOT NULL REFERENCES public.products(id),
  product_name TEXT NOT NULL,
  unit_price NUMERIC(10, 2) NOT NULL,
  quantity INTEGER NOT NULL
);

-- 4. FUNÇÃO PARA DECREMENTAR ESTOQUE DE FORMA SEGURA (RPC)
CREATE OR REPLACE FUNCTION public.decrement_stock(p_product_id BIGINT, p_quantity INT)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  UPDATE public.products
  SET stock = GREATEST(0, stock - p_quantity)
  WHERE id = p_product_id;
END;
$$;

-- 5. CONFIGURAÇÃO DE SEGURANÇA (ROW LEVEL SECURITY - RLS)
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;

-- Políticas de Produtos: Acesso público para leitura da vitrine
DROP POLICY IF EXISTS "Produtos são visíveis publicamente" ON public.products;
CREATE POLICY "Produtos são visíveis publicamente"
  ON public.products FOR SELECT
  USING (true);

-- Permite atualização de estoque pelo backend / RPC
DROP POLICY IF EXISTS "Permite atualização de produtos pelo backend" ON public.products;
CREATE POLICY "Permite atualização de produtos pelo backend"
  ON public.products FOR UPDATE
  USING (true)
  WITH CHECK (true);

-- Políticas de Pedidos: Clientes podem criar pedidos e consultar o recibo
DROP POLICY IF EXISTS "Permite criação de pedidos pública" ON public.orders;
CREATE POLICY "Permite criação de pedidos pública"
  ON public.orders FOR INSERT
  WITH CHECK (true);

DROP POLICY IF EXISTS "Permite consulta de pedidos para recibo" ON public.orders;
CREATE POLICY "Permite consulta de pedidos para recibo"
  ON public.orders FOR SELECT
  USING (true);

-- Políticas de Itens do Pedido
DROP POLICY IF EXISTS "Permite inserção de itens de pedido pública" ON public.order_items;
CREATE POLICY "Permite inserção de itens de pedido pública"
  ON public.order_items FOR INSERT
  WITH CHECK (true);

DROP POLICY IF EXISTS "Permite consulta de itens de pedido para recibo" ON public.order_items;
CREATE POLICY "Permite consulta de itens de pedido para recibo"
  ON public.order_items FOR SELECT
  USING (true);

-- Concede privilégio de execução da função decrement_stock
GRANT EXECUTE ON FUNCTION public.decrement_stock(BIGINT, INT) TO anon, authenticated, service_role;

-- 6. CARGA INICIAL (SEED) DOS 8 CUPCAKES GOURMET
INSERT INTO public.products (id, name, description, price, flavor_tag, image_emoji, stock, ingredients, details)
VALUES
  (
    1,
    'Ninho com Nutella',
    'Massa de leite ninho, recheio cremoso de nutella e cobertura de brigadeiro branco.',
    12.90,
    'Clássico',
    'images/NinhoNutella.jpg',
    30,
    'Leite Ninho integral, Nutella original, leite condensado Moça, manteiga extra sem sal, farinha de trigo especial, ovos selecionados e cacau.',
    'O queridinho absoluto da casa. Nossa massa aerada e fofinha é feita com autêntico Leite Ninho, recheada até o topo com pura Nutella italiana cremosa e coberta por uma generosa camada de brigadeiro branco gourmet aveludado.'
  ),
  (
    2,
    'Red Velvet',
    'Massa aveludada vermelha com cream cheese frosting.',
    14.50,
    'Sofisticado',
    'images/RedVelvet.jpg',
    25,
    'Cacau alcalino suave, cream cheese Philadelphia, extrato natural de baunilha Bourbon, buttermilk artesanal, ovos caipiras e manteiga extra.',
    'A clássica receita nova-iorquina com textura aveludada inconfundível e coloração vermelho-rubi. O topo leva o tradicional cream cheese frosting, que traz o contraste sublime entre a leve acidez do queijo e o toque doce da baunilha.'
  ),
  (
    3,
    'Limão Siciliano',
    'Massa cítrica com curd de limão e merengue maçaricado.',
    13.90,
    'Refrescante',
    'images/LimãoSiciliano.jpg',
    20,
    'Suco e raspas de limão siciliano fresco, ovos, manteiga sem sal, açúcar de confeiteiro, farinha de trigo enriquecida e claras pasteurizadas.',
    'Uma explosão fresca e perfumada. Massa amanteigada enriquecida com raspas frescas de limões sicilianos selecionados, recheada com um curd cremoso artesanal e coroada com merengue suíço sedoso, delicadamente dourado no maçarico.'
  ),
  (
    4,
    'Brigadeiro Gourmet',
    'Clássico brasileiro com granulado belga e recheio generoso.',
    11.90,
    'Clássico',
    'images/BrigadeiroGourmet.jpg',
    40,
    'Chocolate belga 54%, cacau em pó 100% holandês, leite condensado premium, creme de leite fresco e confeitos split Callebaut.',
    'Para quem não abre mão da tradição com requinte. Massa intensa de cacau nobre, recheada com brigadeiro de panela no ponto cremoso de colher e finalizada com autênticos splits de chocolate belga que derretem suavemente na boca.'
  ),
  (
    5,
    'Morango com Chantininho',
    'Massa branca, recheio de morango fresco e chantininho estabilizado.',
    13.50,
    'Frutado',
    'images/MorangocomChantininho.jpg',
    22,
    'Morangos frescos selecionados, leite condensado, leite em pó integral, creme de leite fresco, baunilha e farinha de trigo especial.',
    'Massa branca amanteigada super macia, recheada com compota artesanal de morangos frescos cozidos com um toque de limão, coberta por um suave chantininho estabilizado que une a leveza do chantilly ao sabor marcante do leite em pó.'
  ),
  (
    6,
    'Chocolate Belga com Creme de Avelã',
    'Massa intensa de cacau, recheio trufado de avelã e ganache de chocolate belga.',
    15.90,
    'Premium',
    'images/ChocolateBelgacomCremedeAvelã.jpg',
    25,
    'Cacau holandês 100%, avelãs tostadas inteiras, pasta pura de avelã, chocolate amargo belga 70%, manteiga de cacau e creme fresco.',
    'Nossa criação mais intensa e indulgente. Massa feita com cacau puro 70%, coração trufado com avelãs nobres tostadas artesanalmente e cobertura de ganache acetinada de chocolate belga, decorada com avelã caramelizada.'
  ),
  (
    7,
    'Pistache',
    'Massa amanteigada com creme de pistache importado e lascas crocantes.',
    16.90,
    'Premium',
    'images/Pistache.jpg',
    15,
    'Pistache siciliano puro importado, chocolate branco nobre, leite condensado, manteiga extra, ovos caipiras e flor de sal.',
    'Puro requinte gastronômico. Massa aromática amanteigada com toque de pistache moído na hora, recheada com brigadeiro aveludado de pistache italiano e coberta por lascas crocantes tostadas que adicionam textura inigualável.'
  ),
  (
    8,
    'Caramelo Salgado',
    'Massa de baunilha Bourbon, recheio de caramelo toffee artesanal e toque de flor de sal.',
    14.90,
    'Sofisticado',
    'images/CarameloSalgado.jpg',
    20,
    'Caramelo toffee artesanal, flor de sal de Guérande, extrato puro de baunilha Bourbon, açúcar mascavo, manteiga e creme de leite fresco.',
    'O equilíbrio perfeito entre o dulçor profundo do caramelo cozido lentamente na panela e o toque mineral crocante da flor de sal francesa. A massa é enriquecida com favas de baunilha e a cobertura leva um swirl dourado irresistível.'
  )
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  flavor_tag = EXCLUDED.flavor_tag,
  image_emoji = EXCLUDED.image_emoji,
  stock = EXCLUDED.stock,
  ingredients = EXCLUDED.ingredients,
  details = EXCLUDED.details;

-- Ajusta o contador de sequência para que novas criações de produtos comecem do 9 em diante
SELECT setval('products_id_seq', (SELECT COALESCE(MAX(id), 1) FROM public.products));

-- 7. TABELAS DO BETTER AUTH (AUTENTICAÇÃO E CRIAÇÃO DE CONTAS)
CREATE TABLE IF NOT EXISTS public."user" (
  id TEXT NOT NULL PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  "emailVerified" BOOLEAN NOT NULL DEFAULT false,
  image TEXT,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public."session" (
  id TEXT NOT NULL PRIMARY KEY,
  "expiresAt" TIMESTAMPTZ NOT NULL,
  token TEXT NOT NULL UNIQUE,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "ipAddress" TEXT,
  "userAgent" TEXT,
  "userId" TEXT NOT NULL REFERENCES public."user"(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public."account" (
  id TEXT NOT NULL PRIMARY KEY,
  "accountId" TEXT NOT NULL,
  "providerId" TEXT NOT NULL,
  "userId" TEXT NOT NULL REFERENCES public."user"(id) ON DELETE CASCADE,
  "accessToken" TEXT,
  "refreshToken" TEXT,
  "idToken" TEXT,
  "accessTokenExpiresAt" TIMESTAMPTZ,
  "refreshTokenExpiresAt" TIMESTAMPTZ,
  scope TEXT,
  password TEXT,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public."verification" (
  id TEXT NOT NULL PRIMARY KEY,
  identifier TEXT NOT NULL,
  value TEXT NOT NULL,
  "expiresAt" TIMESTAMPTZ NOT NULL,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

